version: "3.8"
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - MAILTRAP_API_URL=https://sandbox.api.mailtrap.io/api/send/3472284
      - MAILTRAP_API_KEY=0f82d3d172dc9a8fd1b6a13deefbfed3
    networks:
      - portfolio_network
    restart: always
  
  frontend:
    build: ./portfolio_frontend
    ports:
      - "3000:5000"
    depends_on:
      - backend
    networks:
      - portfolio_network

networks:
  portfolio_network:
    driver: bridge
